<a href="https://colab.research.google.com/github/Jimmy586/MachineLearningJourney/blob/master/neuralnetwork_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install opendatasets

In [ ]:
!pip install -q kaggle

In [ ]:
!mkdir -p ~/.kaggle

In [ ]:
import random
import numpy as np
import pandas as pd
import seaborn as sns
import opendatasets as od
import matplotlib.pyplot as plt

In [ ]:
od.download('https://www.kaggle.com/competitions/digit-recognizer/data')

100%|██████████| 15.3M/15.3M [00:00<00:00, 108MB/s] 


Extracting archive ./digit-recognizer/digit-recognizer.zip to ./digit-recognizer


In [ ]:

from matplotlib import pyplot as plt

data = pd.read_csv('./digit-recognizer/train.csv')
data1= pd.read_csv('./digit-recognizer/test.csv')


In [ ]:
data1 = data1.T


In [ ]:
data1 = np.array(data1)
data1.shape

(784, 28000)

In [ ]:
data =  data.T
data = np.array(data)

data.shape

(785, 42000)

In [ ]:
n, m = data.shape
data_dev = data
Y_dev = data_dev[0]
X_dev = data_dev[1:n]
X_dev = X_dev / 255.

data_train = data1
X_train = data_train
X_train = X_train / 255.
_,m_train = X_train.shape

In [ ]:
X_train.shape

(784, 28000)

In [ ]:
def ReLU(Z):
    return np.maximum(Z, 0)

def softmax(Z):
    A = np.exp(Z) / sum(np.exp(Z))
    return A


def ReLU_deriv(Z):
    return Z > 0

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def init_params():
    W1 = np.random.rand(10, 784) * np.sqrt(2 / 784)
    b1 = np.random.rand(10, 1) - 0.5
    W2 = np.random.rand(10, 10) * np.sqrt(2 / 10)
    b2 = np.random.rand(10, 1) - 0.5
    W3 = np.random.rand(10, 10) * np.sqrt(2 / 10)
    b3 = np.random.rand(10, 1) - 0.5
    return W1, b1, W2, b2, W3, b3

def forward_prop(W1, b1, W2, b2, W3, b3, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = ReLU(Z2)
    Z3 = W3.dot(A2) + b3
    A3 = softmax(Z3)
    return Z1, A1, Z2, A2, Z3, A3

def backward_prop(Z1, A1, Z2, A2, Z3, A3, W1, W2, W3, X, Y):
    one_hot_Y = one_hot(Y)
    dZ3 = A3 - one_hot_Y
    dW3 = 1 / m * dZ3.dot(A2.T)
    db3 = 1 / m * np.sum(dZ3)
    dZ2 = W3.T.dot(dZ3) * ReLU_deriv(Z2)
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * ReLU_deriv(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)
    return dW1, db1, dW2, db2, dW3, db3

def update_params(W1, b1, W2, b2, W3, b3, dW1, db1, dW2, db2, dW3, db3, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1
    W2 = W2 - alpha * dW2
    b2 = b2 - alpha * db2
    W3 = W3 - alpha * dW3
    b3 = b3 - alpha * db3
    return W1, b1, W2, b2, W3, b3

In [ ]:
def get_predictions(A3):
    return np.argmax(A3, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2, W3, b3 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2, Z3, A3 = forward_prop(W1, b1, W2, b2, W3, b3, X)
        dW1, db1, dW2, db2, dW3, db3 = backward_prop(Z1, A1, Z2, A2, Z3, A3, W1, W2, W3, X, Y)
        W1, b1, W2, b2, W3, b3 = update_params(W1, b1, W2, b2, W3, b3, dW1, db1, dW2, db2, dW3, db3, alpha)
        if i % 10 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A3)
            print(get_accuracy(predictions, Y))
    return W1, b1, W2, b2, W3, b3


In [ ]:
W1, b1, W2, b2, W3, b3 = gradient_descent(X_dev, Y_dev, 0.010, 100000)

Streaming output truncated to the last 5000 lines.
[1 0 1 ... 7 6 9] [1 0 1 ... 7 6 9]
0.9457380952380953
Iteration:  51820
[1 0 1 ... 7 6 9] [1 0 1 ... 7 6 9]
0.9457380952380953
Iteration:  51830
[1 0 1 ... 7 6 9] [1 0 1 ... 7 6 9]
0.9457380952380953
Iteration:  51840
[1 0 1 ... 7 6 9] [1 0 1 ... 7 6 9]
0.9457380952380953
Iteration:  51850
[1 0 1 ... 7 6 9] [1 0 1 ... 7 6 9]
0.9457380952380953
Iteration:  51860
[1 0 1 ... 7 6 9] [1 0 1 ... 7 6 9]
0.9457142857142857
Iteration:  51870
[1 0 1 ... 7 6 9] [1 0 1 ... 7 6 9]
0.9457142857142857
Iteration:  51880
[1 0 1 ... 7 6 9] [1 0 1 ... 7 6 9]
0.9457142857142857
Iteration:  51890
[1 0 1 ... 7 6 9] [1 0 1 ... 7 6 9]
0.9457142857142857
Iteration:  51900
[1 0 1 ... 7 6 9] [1 0 1 ... 7 6 9]
0.9457380952380953
Iteration:  51910
[1 0 1 ... 7 6 9] [1 0 1 ... 7 6 9]
0.9457142857142857
Iteration:  51920
[1 0 1 ... 7 6 9] [1 0 1 ... 7 6 9]
0.9457142857142857
Iteration:  51930
[1 0 1 ... 7 6 9] [1 0 1 ... 7 6 9]
0.9457142857142857
Iteration:  51940


In [ ]:
def make_predictions(X, W1, b1, W2, b2):
    _, _, _, A2 = forward_prop(W1, b1, W2, b2, X)
    predictions = get_predictions(A2)
    return predictions

def test_prediction(index, W1, b1, W2, b2):
    current_image = X_train[:, index, None]
    prediction = make_predictions(X_train[:, index, None], W1, b1, W2, b2)
    print("Prediction: ", prediction)

    current_image = current_image.reshape((28, 28)) * 255
    plt.gray()
    plt.imshow(current_image, interpolation='nearest')
    plt.show()


In [ ]:
for i in range(1000,1050):
  test_prediction(i, W1, b1, W2, b2)


NameError: ignored